name: generic_olm_bindings
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.76.0
  meta: ^1.9.0

dev_dependencies:
  ffigen: ^8.0.0
  lints: ^2.0.0
  test: ^1.21.0
  checks: ^0.2.0
