name: vodozemac
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  ffi: ^2.0.1
  flutter_rust_bridge: ^2.9.0
  import_sorter: ^4.6.0
  meta: ^1.9.0
  test_core: ^0.6.8
  uuid: ^4.4.2
  frontend_server_client: ^4.0.0

dev_dependencies:
  ffigen: ^18.1.0
  lints: ^5.1.1
  test: ^1.21.0
  checks: ^0.3.0

flutter_rust_bridge:
  rust_input: crate::bindings
  rust_root: ../rust
  dart_output: lib/src/generated
  web: true
  dart_format_line_length: 120
  dart3: false
  full_dep: true