name: vodozemac
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  flutter_rust_bridge: ^2.9.0
  test_core: ^0.6.8

dev_dependencies:
  lints: ^5.1.1
  test: ^1.21.0
  checks: ^0.3.0
  import_sorter: ^4.6.0
  ffigen: ^18.1.0

import_sorter:
  comments: false
  ignored_files: # ignore generated files
    - \/lib\/src\/generated\/*